# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfce6f5251e0a125020267f8b8f60ee9689c8518445cfc6ada191ced479d25db4e74c4b1504719a151790540d32747ad61edeac6ecb7cb56f77b28759d0d9ab0

test:
  secret_key_base: ade285465dad0decfd8cda742abdbd5f4a695e0623919880db08a76e51420d046d6f1dd41d8b49428c878134371506b71ad6472e0ebcaa3188fb83fc7bded0a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
